FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expse the backend port
EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "attendance_saas.wsgi:application"]
