# Generated by Django 6.0.8 on 2026-08-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
