# Generated by Django 4.2.30 on 2026-09-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bound_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('verify', 'Verification'), ('reset', 'Password Reset'), ('rebind', 'Device Rebind')], default='verify', max_length=20),
        ),
    ]
