# Generated by Django 4.2.30 on 2026-09-14 15:47

from django.db import migrations
import uuid

def migrate_device_data(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    DeviceBinding = apps.get_model('accounts', 'DeviceBinding')
    
    # Iterate over all students who have a bound_device_id
    for user in CustomUser.objects.filter(role='student', bound_device_id__isnull=False).exclude(bound_device_id=''):
        try:
            # We must use a valid UUID. The old device_id might be a string like "test-device-uuid-1234"
            # We can hash the old string to create a valid UUID, or just generate a new one.
            # Wait, if we generate a new one, the user will be logged out anyway since the cookie is missing.
            # But we want to preserve the "bound" state so they don't have to rebind.
            # A deterministic UUID from the old ID is best.
            import hashlib
            old_id = str(user.bound_device_id).encode('utf-8')
            new_uuid = uuid.UUID(bytes=hashlib.md5(old_id).digest())
            DeviceBinding.objects.create(
                user=user,
                token=new_uuid,
                user_agent="Migrated from old system"
            )
        except Exception:
            pass

def reverse_device_data(apps, schema_editor):
    DeviceBinding = apps.get_model('accounts', 'DeviceBinding')
    DeviceBinding.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_devicebinding'),
    ]

    operations = [
        migrations.RunPython(migrate_device_data, reverse_device_data),
    ]
