# Generated by Django 4.2.30 on 2026-09-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20260914_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bound_device_id',
        ),
    ]
