# Generated by Django 4.2.30 on 2026-09-21 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_bound_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeviceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_device_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('device_fingerprint', 'date')},
            },
        ),
    ]
