# Generated by Django 4.2.30 on 2026-07-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
