# Generated by Django 6.0.8 on 2026-08-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_domain'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'institution')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'department')},
        ),
    ]
