# Generated by Django 4.2.30 on 2026-07-02 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses_taught', through='courses.CourseInstructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
