# Generated by Django 6.0.8 on 2026-08-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_fix_schema'),
        ('institutions', '0003_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'department', 'section')},
        ),
    ]
